# Site settings
title: NCK Blog
url: "https://nckdz.github.io"
baseurl: ""
description: >
  Một blog mới sử dụng Jekyll.

# Your information
email: nck9z2015@gmail.com
author: Nguyễn Định
profile_links:
  Email: "mailto:nck9z2015@gmail.com"
  GitHub: "https://github.com/nckdz"

header:
  links:
    About: /about/
    Category: /category/
    Donate: /donate

plugins:
 - jekyll-paginate

# Build settings
paginate: 5
paginate_path: "page:num"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

# html minify
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]